# Generated by Django 5.0.2 on 2024-03-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0008_alter_appuser_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
