# Generated by Django 5.0.2 on 2024-03-05 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0010_remove_transaction_id_appuser_transaction_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField( editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='transaction_pin',
            field=models.IntegerField(unique=True),
        ),
    ]
