# Generated by Django 5.0.2 on 2024-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0012_transaction_receiver_transaction_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='transaction_pin',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
