# Generated by Django 5.0.2 on 2024-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0013_alter_appuser_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='transaction_pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
