# Generated by Django 5.0.2 on 2024-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0018_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
