# Generated by Django 5.0.2 on 2024-03-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0021_alter_appuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='transaction_pin',
            field=models.CharField(max_length=4),
        ),
    ]
