# Generated by Django 5.0.2 on 2024-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0025_demataccount_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='DematAccount',
        ),
    ]
